### ISSUE TITLE
Enable `algebra::VectorKD` to be converted to list

### ISSUE THREAD

**Issue by sdaxen** [salilab/imp#1019]
It seems that when converting an `IMP::algebra::VectorKD` to a Python list, it's length is not used, so the operation fails:

```python
>>> import IMP.algebra
>>> v = IMP.algebra.Vector3D([1, 2, 3])
>>> v
(1, 2, 3)
>>> list(v)
[1.0, 2.0, 3.0]
>>> v = IMP.algebra.VectorKD([1, 2, 3])
>>> v
(1, 2, 3)
>>> len(v)
3
>>> list(v)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/saxen/projects/imp/build/debug/lib/IMP/algebra/__init__.py", line 3160, in __getitem__
    return _IMP_algebra.VectorKD___getitem__(self, index)
_IMP_kernel.InternalException: Internal check failure: Invalid component of vector requested: 3 of 3
  File "include/IMP/algebra/VectorBaseD.h", line 68
```

**Comment by sdaxen** [comment]
I actually don't understand why `VectorKD` works in Python at all, given the definition of `__getitem__` for `IMP.algebra.Vector<D>` and that `D=-1` for `VectorKD`.
https://github.com/salilab/imp/blob/46ec3e3e0601ef5d9ae8c45c4e660c0decbf98f0/modules/algebra/pyext/IMP_algebra.vector.i#L38-L41

**Comment by benmwebb** [comment]
Hmm, clearly a bug. Odd though because the length does seem to be defined and Python should be using it (since we don't provide an iterator for `VectorKD`).

>     if (index >= D) throw IMP::IndexException(""); 

Since one of the two arguments here (`index`) is unsigned, an unsigned comparison is used. Signed -1 is equal to unsigned 2^32-1, so this will almost never be true. The code is clearly broken for the D=-1 case though.
