### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by celinasjose** [salilab/imp#1052]
I installed version 2.5 from source 
> cmake ../imp-2.5.0 -DCMAKE_BUILD_TYPE=Release -DIMP_MAX_CHECKS=NONE -DIMP_MAX_LOG=SILENT -DPYTHON_LIBRARY=/mnt/i3S/homes/cjose/anaconda3/lib/libpython3.8.so -DPYTHON_INCLUDE_DIR=/mnt/i3S/homes/cjose/anaconda3/include/python3.8/ -DPYTHON_EXECUTABLE=/mnt/i3S/homes/cjose/anaconda3/bin/python3.8 -DSWIG_EXECUTABLE=/mnt/i3S/homes/cjose/anaconda3/bin/swig
> make -j4

and obtained the following error:
```[ 77%] Linking CXX executable em/benchmark_density
[ 77%] Built target IMP.em-benchmark_density.cpp
make: *** [all] Error 2
```

Can you help me solve this issue?
Thanks

**Comment by benmwebb** [comment]
> I installed version 2.5 from source

Why? 2.5 is over 5 years old. You might be able to make it work, but it'll require either first installing similarly old versions of each of its dependencies, or backporting various fixes to make it work with modern versions of cmake, boost, gcc, python, etc. Why can't you use the latest version?

>  and obtained the following error:

    [ 77%] Built target IMP.em-benchmark_density.cpp 
    make: *** [all] Error 2

That's just the last two lines of the output, which don't show the actual error. You'll need to look further up in the output to find the real problem.

**Comment by celinasjose** [comment]
I am using IMP for another tool that states recent versions might crash.

You can find the full error attached.
[error_imp.txt](https://github.com/salilab/imp/files/6148760/error_imp.txt)

**Comment by benmwebb** [comment]
> I am using IMP for another tool that states recent versions might crash.

Which tool? If there is a problem with IMP > 2.5, the author of that tool should report the issue so we can fix it. Otherwise, my guess is they haven't tested the tool with later versions. We can't support versions of the code that old.

> You can find the full error attached.

This looks like you have tried to build old IMP with new tools (specifically, SWIG 4). Obviously old IMP can't necessarily support being built with new tools, since they didn't exist at the time. You'll either need to build IMP on a similarly-old machine (perhaps running CentOS 5 or Ubuntu 14.04) or you'll need to dig through the last 5 years of our changes and try to backport any that fix issues with newer tools. The specific error you're running into is

> /mnt/i3S/homes/cjose/Software/IMP/swig/IMP_atom.impl.i:276: Error: 'IMP::core::show' resolves to 'IMP::core::show' and was incorrectly instantiated in scope 'IMP::atom' instead of within scope 'IMP::core'.

This is probably fixed by [backporting the commit](https://github.com/salilab/imp/commit/5dbf77dac329) that fixed this issue with SWIG 4, but likely then you will run into a different issue.
