### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#1066]
imp fd347957c839f2241ed4847be2e04349e0407580
on mac os 12.2.1, with updated xtools, homebrew salilab library updated

cmake -G Ninja ../imp -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/usr/local/opt/boost/

...
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
...
Found Boost: /usr/local/opt/boost/include (found suitable version "1.79.0", minimum required is "1.53.0")
...

I've got the compilation error attached.
Wrong boost verision? wrong compiler?

[error.txt](https://github.com/salilab/imp/files/9054032/error.txt)

**Comment by benmwebb** [comment]
The specific error here is

```
/usr/local/include/boost/math/tools/config.hpp:386:62: error: unknown type name 'noexcept'
```

`noexcept` is a C++11 keyword, so either you are using an ancient compiler or you have set an option like `-std` that asks the compiler to compile for an older C++ standard. IMP certainly builds fine in this environment, e.g. https://integrativemodeling.org/nightly/logs/develop/20220704/mac12-intel/ALL.build.log

BTW, if you are using boost from Homebrew, there is no need to set `BOOST_ROOT`. And when building on Mac I would recommend running cmake with `-DCMAKE_CXX_FLAGS="-std=c++17"` since some support libraries such as CGAL insist on newer C++ standards.
