### ISSUE TITLE
Cant find imp modul

### ISSUE THREAD

**Issue by QFirebal** [salilab/imp#1085]
Hi,

i am on windows and trying to get an dashboard apllication running over python. I am complete new to python and i nearly got everything running but curently it seems like my python cant find the imp modul.
`Python\Python312\Lib\site-packages\salsa20.py", line 11, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'`
this is the Python version i am using
`Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.`

i have alreday downlaoded the Windows version 2.19.0 from https://integrativemodeling.org/download.html and installed it. But after a restart i recive the same output and imp is not listed when i use `pip list`

**Comment by benmwebb** [comment]
If you are really trying to find Python's built-in `imp` module, you are in the wrong place. This is `IMP`. The `imp` package was removed from Python in Python 3.12: https://docs.python.org/3/whatsnew/3.12.html. Either contact the authors of the `salsa20` package and have them update it, or use an older version of Python.

If you really trying to use `IMP`, IMP 2.19.0 was released in June, well before Python 3.12 was released, so the installer does not include Python 3.12 support. If you really need support for Python 3.12, you can either install Anaconda Python instead and then install the IMP conda package from https://integrativemodeling.org/download-anaconda.html; the conda-forge folks just [added Python 3.12 support](https://conda-forge.org/docs/user/announcements.html#python-3-12-migration-and-python-3-11-by-default); or you can use a [nightly development build](https://integrativemodeling.org/download.html#develop). Otherwise, I suggest you stick with Python 3.11 for now.

**Comment by QFirebal** [comment]
The solution with downgrading to 3.11 worked the dashboard is running now thank you very much.
