### ISSUE TITLE
CHARMM topology doesn't set up hierarchy correctly

### ISSUE THREAD

**Issue by cgreenberg** [salilab/imp#866]
After setting up a hierarchy with:
```python
ff = IMP.atom.get_heavy_atom_CHARMM_parameters()
t = ff.create_topology(h)
```
I find that some of the particles are not XYZRs and not Atoms. I don't really understand what the topology is doing so I don't know if this is intended. All I know is that you get a failure if you add these lines to any of the tests in atom/test_create_topology.py:
```python
check_atom=[p for p in IMP.core.get_leaves(h) if not IMP.atom.Atom.get_is_setup(p)]
self.assertEqual(len(check_atom),0)
```
Same thing if you do `IMP.core.XYZR.get_is_setup(p)`. I guess the topology is adding and deleting atoms, but not setting them up correctly?

**Comment by cgreenberg** [comment]
Quick ammendment: I was looking at the wrong test. The problem is specifically that the topology doesn't set particles up as XYZR. I'll add the test.

**Comment by benmwebb** [comment]
`create_topology()` doesn't make particles - it makes a `CHARMMTopology` object which can be used to make particles later (usually with `setup_hierarchy()`).

`setup_hierarchy()` doesn't make XYZR particles. If you want radii, then add them by calling `add_radii()`. Radii aren't needed for stereochemistry, which is why the stereochemistry tests don't add them.
