### ISSUE TITLE
PairsRestraint deprecated?

### ISSUE THREAD

**Issue by yannickspill** [salilab/imp#877]
`container::create_restraint` defined in `container/include/generic.h` has the following comment
```
Create a restraint from a score and a container. The resulting restraint is, in general, more efficient than creating an, eg, PairsRestraint.
```
Does it mean that `PairsRestraint` should not be used, and should therefore be seen as deprecated?

**Comment by benmwebb** [comment]
If it were deprecated you'd get an annoying deprecation warning every time you used it ;)

Generic restraints combine the parts at compile time (using templates) rather than at runtime. In principle this means the C++ compiler can do a better job of optimizing the code (e.g. removing virtual function calls) resulting in faster code. But you can't do that with anything plugged in at runtime (e.g. Python). So we have both mechanisms.

**Comment by yannickspill** [comment]
so why interface this call to python and still keep PairsRestraint?

**Comment by benmwebb** [comment]
You can't make a Python interface to all possible generic restraints, since you need to recompile IMP in order to persuade the compiler to generate the code. But it's not unreasonable to generate a commonly-used subset (e.g. harmonic distance restraints).
