### ISSUE TITLE
Selection - get highest nodes matching fields?

### ISSUE THREAD

**Issue by cgreenberg** [salilab/imp#896]
Would it be possible to add a function to Selection that, instead of getting the selected particles, gets the highest node(s) matching the criteria? Currently, for example, if I want to select the molecule named "abc" I have to do this:

`mol = IMP.atom.get_molecule(IMP.atom.Selection(root,molecule="abc").get_selected_particles()[0])`

or this:

`mol = [h for h in IMP.atom.get_by_type(root,IMP.atom.MOLECULE_TYPE) if \\ 
IMP.atom.Molecule(h).get_name()=='abc'][0]`

**Comment by benmwebb** [comment]
Selection gives you all the particles for which all of the predicates are true or not applicable - that's why you get all the children of the abc molecule (because they're not `Molecule`s, so the `molecule="abc"` predicate isn't applicable). We can't easily exclude searching the children because there might be another predicate (e.g. `residue_index=133`) which could fail.

It might be possible to get the behavior you describe to work, perhaps just in simple cases where you have a single predicate (it would be difficult to make it work with any of the and/or/xor selections, for sure). Write a test case that exercises this behavior (which will obviously fail for now) and I'll take a look.

**Comment by cgreenberg** [comment]
Will do! This will be super useful, for example, when setting up certain kinds of movers. E.g. the super rigid body may act on a Molecule or Fragment level, so we'll want easy access to retrieve those.

**Comment by benmwebb** [comment]
Closed by 4a4ab10.
