### ISSUE TITLE
Windows 7 installation fails finding "par.lib" file during IMP.atom.read_pdb

### ISSUE THREAD

**Issue by Elincath** [salilab/imp#923]
We have a windows 7
Python: Canopy or PythonIDLE  
IMP binary release : IMP-20160119.develop.929715a-64bit, 

running the following simple test:

```
import IMP 
import IMP.core
import IMP.atom

m=IMP.Model()
h=IMP.atom.read_pdb("../data/comfa_model1.pdb",m)
```

we get:
```
---------------------------------------------------------------------------
 IOException                               Traceback (most recent call last)
 c:\users\proteoms\appdata\local\temp\tmpzxdaii.py in <module>()
       4 
       5 m=IMP.Model()
 ----> 6 h=IMP.atom.read_pdb("../data/comfa_model1.pdb",m)

C:\Program Files\IMP-20160119\python\IMP\atom\__init__.py in read_pdb(*args)
   13344     read_pdb(TextInput input, int model, Hierarchy h)
   13345     """
 > 13346     return _IMP_atom.read_pdb(*args)
   13347 
   13348 def read_multimodel_pdb(*args):

IOException: Unable to find data file par.lib in [/usr/local/share/IMP]. IMP is not installed or set up correctly.
```

**Comment by Elincath** [comment]
same for IMP release 2.5.0

**Comment by benmwebb** [comment]
Hmm, this is because the `.exe` package looks in the Windows Registry for its install location, but it's looking in the wrong place. Should be easy to fix in the nightly builds, and I'll look into rebuilding the 2.5.0 package with the fix. As a workaround for now, you can either install the Anaconda package (this should be truly relocatable) or you can fire up `regedit` and copy the `HKEY_LOCAL_MACHINE\SOFTWARE\IMP-2.5.0` key to `HKEY_CURRENT_USER\SOFTWARE\IMP-2.5.0`.

**Comment by benmwebb** [comment]
The nightly builds should work now.

**Comment by Elincath** [comment]
I have installed the nightly builds and everything is working fine now :)
Thanks a lot
