### ISSUE TITLE
Link ipython notebook examples on the examples page

### ISSUE THREAD

**Issue by cgreenberg** [salilab/imp#944]
Anything we can do to link these from the manual? Perhaps a web viewer for these notebooks?
https://github.com/salilab/pmi/blob/develop/examples/cross-link/cross-link_ms.ipynb

**Comment by benmwebb** [comment]
I'm not a huge fan of ipython notebook examples, since people with "regular" Python can't see them. (And, as you point out, they don't get picked up by doxygen properly, or tested by the build system, since those can't parse `ipynb` files either.) What you do you really lose by converting them to regular `.py` files?

**Comment by benmwebb** [comment]
Note that none of the `ipynb` examples show up, because they don't use the doxygen `\example` tag like the other examples. You'll need to add that.

**Comment by benmwebb** [comment]
These examples were moved out into a standalone tutorial: https://integrativemodeling.org/tutorials/cross_linking/
