### ISSUE TITLE
IMP and local install of Anaconda

### ISSUE THREAD

**Issue by fergaljd** [salilab/imp#960]
I am trying to run the tutorial for IMP here - https://integrativemodeling.org/2.6.2/doc/manual/rnapolii_2.html

When I try to run "python modeling.py --test", I get an error message: 

```
  File "C:\Users\fduffy\AppData\Local\Continuum\Anaconda2\lib\site-packages\IMP\atom\__init__.py", line 13471, in read_pdb
    return _IMP_atom.read_pdb(*args)

IOException: Unable to find data file par.lib in [C:/Users/ben/Miniconda3/envs/_build_placehold_placehold_placehold_placehold_plac/Library/share/IMP]. IMP is not installed or set up correctly.
```

I installed IMP using Anaconda, which is installed locally. I'm pretty sure the par.lib file is present on my machine at
C:\Users\fduffy\AppData\Local\Continuum\Anaconda2\Library\share, 
but it appears that IMP is looking in the wrong place. Is there a way to fix this, or set the path manually?

**Comment by benmwebb** [comment]
Hmm, that's odd. Anaconda is supposed to detect such hard-coded paths (that's what the `placehold_placehold` path is for) and replace them with the correct path for your installation. I don't know why it's not doing that since it certainly works on Mac and Linux (but just checked on a spare Windows box, and I see the same problem). I'll see if I can figure out what's going on and get back to you. Unfortunately I don't think there's an easy workaround in the meantime since these paths are hardcoded into the `imp_kernel.dll` binary (short of changing the binary with a hex editor, or making the directory it's looking for and copying `par.lib` there).

**Comment by benmwebb** [comment]
Looks like an Anaconda bug (feature?) Paths like these aren't replaced on Windows, as per conda/conda@d4c0fab98. I'm not sure why this was done, but it looks to me like the latest conda at GitHub no longer has this problem... so the next time conda is updated it *should* go away.

**Comment by benmwebb** [comment]
> so the next time conda is updated

More specifically, looks like this is fixed in [conda 4.2.2](https://github.com/conda/conda/releases/tag/4.2.2) but that's still considered a pre-release, sorry. The conda folks probably have an idea when that will become available via the regular `conda update`.

**Comment by benmwebb** [comment]
A workaround in the meantime that works for me is to downgrade conda to 4.0 (at least long enough to install IMP):

    conda uninstall imp
    conda install conda=4.0.11
    conda install imp conda=4.0.11

**Comment by fergaljd** [comment]
Thanks for the help - I tried the workaround you suggested above, and it works for me.

It sure seems like an odd decision by Anaconda to single out Windows for strange install treatment.

**Comment by benmwebb** [comment]
Just FYI, looks like the Anaconda folks randomly broke this again in 4.2.10, with conda/conda@4764dff51b. An updated workaround is:

    conda uninstall imp
    conda install conda=4.2.9
    conda install imp conda=4.2.9
