### ISSUE TITLE
Store Sequence attribute to a Molecule/Fragment/Chain

### ISSUE THREAD

**Issue by Pellarin** [salilab/imp#965]
Maybe is silly, but is there a way to store the one-letter-code sequence associated to a molecule/chain/fragment hierarchy? If not, what about a IMP.atom.Sequence hierarchy decorator?

**Comment by benmwebb** [comment]
No, not to my knowledge. Why not just add the sequence to the Fragment decorator? Or maybe you can think of a use case where you'd need to attach a sequence to something that isn't a fragment. I just want to avoid the ambiguity that would arise if you ever have a Sequence and a bunch of Residue objects at the same point in the hierarchy (which sequence would you believe then? what happens if they're different?)

**Comment by Pellarin** [comment]
I think that we can add sequence as a string uniquely to IMP.atom.Molecule decorator. That would make absolutely sense. I don't know how to handle it in RMF, though.

**Comment by benmwebb** [comment]
Chain would make more sense, otherwise you have to worry about handling chain breaks in the sequence. I can handle this in IMP and RMF.

**Comment by Pellarin** [comment]
well also chains can be broken, can't they?

**Comment by Pellarin** [comment]
However, IMP.atom.Chain is fine with me, as all Molecules in PMI are also decorated as Shains.

**Comment by benmwebb** [comment]
> well also chains can be broken, can't they?

Sure, so checking that the sequence matches that of any child Residue objects will be non-trivial in the general case. This is why I originally suggested adding the sequence to each Fragment object (those can be broken too, and have other problems). But I think Chain is our best option.

**Comment by Pellarin** [comment]
Thanks! We should also add another Chain attribute: the sequence might be "Protein", "RNA", "DNA" (or maybe other proteins). It cannot be detected directly from the one letter code, since for instance "AAAAAA" can both be Alanines of Adenosines.

**Comment by Pellarin** [comment]
If we agree on a scheme, I might implement it myself following what your last commit.

**Comment by benmwebb** [comment]
> sequence might be "Protein", "RNA", "DNA"

One option would be the Modeller solution, where lower case is used for nucleic acids (so "aaa" is easily distinguished from "AAA"). The only problem then is distinguishing RNA from DNA.

If you really want to add another Chain attribute, I'm not sure what other values it could take beyond those three options (but we can always add more later I suppose).

> I might implement it myself

The RMF support will be tricky, so you'll probably want to leave it to me ;) It should be an enumeration rather than just free text, and we'd need to support a default, otherwise RMF will fail to read in any RMF file generated prior to this change (since the Chains won't have the right attributes).

**Comment by Pellarin** [comment]
Maybe also "Glycan"? Though not a lot of people is working with that polymer.
