### ISSUE TITLE
name conflict with python imp

### ISSUE THREAD

**Issue by SHZ66** [salilab/imp#970]
Hi,

I followed the installing instruction to install IMP via Anaconda. However I got this error:

```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications .......

The following specifications were found to be in conflict:
  - imp
Use "conda info <package>" to see the dependencies for each package.
```

I think it conflicts with this [Python module](https://docs.python.org/2/library/imp.html). Any solution or workaround would be appreciated. Thanks.

**Comment by benmwebb** [comment]
> I think it conflicts with this Python module

That can't be right because then it would work nowhere. The 'imp' Python module is part of the standard library. It doesn't conflict with our package because our package is called 'IMP' and there is no Anaconda package for the 'imp' Python module anyway (it's part of the 'python' Anaconda package). This conflict must come from somewhere else. Is that the full error message? What platform are you trying to install the package on?

**Comment by SHZ66** [comment]
Thanks for the reply.

I agree that this is such a weird error because I was able to install and import IMP on my other linux machine without the conflict. The one with the problem is a Mac (OSX 10.11.6), and what I did is:
```
conda config --add channels salilab
conda install imp
```
and it then showed
```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications .......

The following specifications were found to be in conflict:
  - imp
Use "conda info <package>" to see the dependencies for each package.
```

My Python version is 2.7.11; Conda is 4.1.1.

**Comment by benmwebb** [comment]
Odd, I just tried this on my 10.11.6 Mac starting from a fresh miniconda install and it worked fine:

    $ sw_vers -productVersion
    10.11.6
    $ sh Miniconda2-4.1.11-MacOSX-x86_64.sh
    [...]
    $ conda config --add channels salilab
    $ conda install imp
    Fetching package metadata .........
    Solving package specifications: ..........
    
    Package plan for installation in environment /Users/ben/miniconda2:
    
    The following packages will be downloaded:
    [...]

The fact that conda is saying that there is a conflict between imp and... nothing is odd. Something looks screwed up there. You could try a `conda info imp`, find the Python 2.7 version, and try installing each dependency one by one to see what's tripping conda up (e.g. `conda install gsl=1.16`). Or you could try a `conda --debug install imp` and see if the debug output indicates anything weird going on. Or maybe you just need to do a `conda update --all` and/or a `conda clean --all` first. Or maybe you have another Anaconda channel in `~/.condarc` that's confusing things? (If so, I can try the same channel on my machine and see if I get the same problem.)

Any how, I'm not sure what the problem is here, but hopefully one of the things I suggest above can shed some light on the problem.

**Comment by SHZ66** [comment]
Thanks for the suggestions.

I looked at `~/.condarc`, there are three channels:
```
- salilab
- conda-forge
- defaults
```
everything looks normal there I think.  I will try your other suggestions and post which one solves the problem.

**Comment by benmwebb** [comment]
FWIW, I refreshed the Mac IMP packages today (they were built on a 10.6 machine before; now they're built on a 10.9 machine to be consistent with the rest of Anaconda). This was done to add Python 3.6 support, not specifically to address your issue, but something may change as a result.

**Comment by benmwebb** [comment]
@SHZ66  Was this resolved for you?

**Comment by SHZ66** [comment]
It didn't immediately work, but then I reinstalled Anaconda and I had no problem installing IMP. Thank you!
