### ISSUE TITLE
adding content to RMF files

### ISSUE THREAD

**Issue by shanot** [salilab/imp#975]
Is it possible to add information about particles in the RMF, such as:

-Reference information
-Copy number

This would be very useful for analysis if we need to know which protein is a copy (and/or reference) of which.
As far as I know the Reference and Copy decorator information is not stored in the RMF so I have to fall back to more artisanal techniques such as parsing the copy id from the full name.

**Comment by benmwebb** [comment]
It's certainly possible to add extra data - it's just not currently done. Copies are a bit more involved though, since in many cases it would make more sense to not duplicate the node in the RMF file (but rather to add a pointer to the original node, perhaps with a transformation). Certainly for big symmetric complexes it wastes a lot of space in the RMF to store symmetry-related components.

**Comment by cgreenberg** [comment]
Well Copies in PMI (or IMP) are not enforced to be the same, so you probably don't want to do that in RMF. There is a PMI "clone" but that's an informal part of the construction process that ensures the hierarchy structure is the same. The structures themselves could be flexibly different. It would be good just to have the copy number (although that may already be in there...)

**Comment by benmwebb** [comment]
Perhaps I wasn't clear but I was talking about symmetry-constrained components, not *all* Copies.

The copy number (assuming you're using the `atom::Copy` decorator) is already stored in RMF files. `core::Reference` information isn't, but I don't think it would be hard to add. I'll take a look.

**Comment by shanot** [comment]
Thanks !
